### ISSUE TITLE
Please give me the owner permission

### ISSUE THREAD

**Issue by inouetakuya** [pepabo/active_merchant-epsilon#86]
Hi, @kurotaky 

I would like to push gem https://rubygems.org.

Please give me (inouetakuya5@gmail.com) owner permission.

ref. error message which I have gotten

> Pushing gem to https://rubygems.org...
> You do not have permission to push to this gem. Ask an owner to add you with: gem owner active_merchant-epsilon --add inouetakuya5@gmail.com

**Comment by kurotaky** [comment]
@inouetakuya 
I added you to gem owner, please check it now! :)
```
Owner added successfully.
Owners for gem: active_merchant-epsilon
- inouetakuya5@gmail.com
- yuta.kurotaki@gmail.com
```

**Comment by inouetakuya** [comment]
Thank you !!

I pushed gem to rubygems.org successfully 🎉
